CREATE TABLE USERS
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   USERNAME TEXT DEFAULT "username" NOT NULL,
   PASSWORD TEXT DEFAULT "password" NOT NULL,
   UNIQUE (USERNAME)
);
CREATE TABLE LOCATIONS
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   NAME TEXT DEFAULT "locationName" NOT NULL,
   UNIQUE (NAME)
);
CREATE TABLE ITEMS
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   NAME TEXT DEFAULT "Name" NOT NULL
);
CREATE TABLE I18N_ITEMS
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   ITEM_ID INTEGER,
   LANGUAGE TEXT DEFAULT "ru",
   TRANSLATION_NAME TEXT,
   TRANSLATION_DESCRIPTION TEXT,
	   FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID),
   UNIQUE
   (
      ITEM_ID,
      LANGUAGE
   )
);
CREATE TABLE CATEGORIES
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   NAME TEXT DEFAULT "name" NOT NULL,
   UNIQUE (NAME)
);
CREATE TABLE GLOBAL_SETTINGS
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   NAME TEXT DEFAULT "name" NOT NULL,
   UNIQUE (NAME)
);
CREATE TABLE I18N_SETTINGS
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   SETTING_ID INTEGER,
   LANGUAGE TEXT DEFAULT "en" NOT NULL,
   TRANSLATION TEXT DEFAULT "translation" NOT NULL,
   UNIQUE
   (
      SETTING_ID,
      LANGUAGE,
      TRANSLATION
   )
);
CREATE TABLE SETTING_VALUE
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   SETTING_ID INTEGER,
   USER_ID INTEGER,
   VALUE INTEGER,
   UNIQUE
   (
      SETTING_ID,
      USER_ID,
      VALUE
   )
);
CREATE TABLE ITEM_CATEGORY
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   ITEM_ID INTEGER,
   CATEGORY_ID INTEGER,
   FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID),
   FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
   UNIQUE
   (
      ITEM_ID,
      CATEGORY_ID
   )
);
CREATE TABLE ITEM_LOCATION
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   ITEM_ID INTEGER,
   LOCATION_ID INTEGER,
   FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID),
   FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (ID),
   UNIQUE (ITEM_ID)
);
CREATE TABLE ITEM_USER
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   ITEM_ID INTEGER,
   USER_ID INTEGER,
   FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID),
   FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
   UNIQUE (ITEM_ID)
);