Drop TABLE LECTURES IF EXISTS;
CREATE TABLE LECTURES(
	LECTURE_ID serial,
	TIMESLOT int,
	TEACHER_ID int,
	COURSE_ID int,
	GROUP_ID int,
	ROOM_NUMBER int,
	WEEK int,
	WEEKDAY varchar(255),

UNIQUE(LECTURE_ID,ROOM_NUMBER,TIMESLOT,WEEK,WEEKDAY)
);