DROP TABLE PERSONS IF EXISTS;
DROP TABLE STUDENTS IF EXISTS;
DROP TABLE TEACHERS IF EXISTS;
DROP TABLE ADMINS IF EXISTS;

CREATE TABLE PERSONS(
	PERSON_ID serial,
	NAME  varchar(255),
	USERS_PASSWORD  varchar(255),
        FACULTY varchar(255),
        ROLE varchar(255),
UNIQUE(NAME,FACULTY,ROLE)
);

 CREATE TABLE STUDENTS(
        PERSON_ID int,
        GROUP_ID int,
 UNIQUE(PERSON_ID,GROUP_ID)
 );

 CREATE TABLE TEACHERS(
        PERSON_ID int,
        ACADEMIC_DEGREE varchar(255),
 UNIQUE(PERSON_ID,ACADEMIC_DEGREE)
 );

 CREATE TABLE ADMINS(
        PERSON_ID int,
        POSITION varchar(255),
 UNIQUE(PERSON_ID,POSITION)
 );
