DROP TABLE IF EXISTS UNIVERSITY_GROUPS;
DROP TABLE IF EXISTS PERSONS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS ADMINS;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS LECTURES;

CREATE TABLE UNIVERSITY_GROUPS
(
   GROUP_ID serial,
   GROUP_NAME varchar (255),
   UNIQUE (GROUP_NAME)
);
CREATE TABLE PERSONS
(
   PERSON_ID serial,
   NAME varchar (255),
   USERS_PASSWORD varchar (255),
   FACULTY varchar (255),
   ROLE varchar (255) CHECK (ROLE='STUDENT' OR ROLE='TEACHER' OR ROLE='ADMIN'),
   UNIQUE
   (
      NAME,
      FACULTY,
      ROLE
   )
);
CREATE TABLE STUDENTS
(
   PERSON_ID INTEGER,
   GROUP_ID INTEGER,
   UNIQUE
   (
      PERSON_ID,
      GROUP_ID
   )
);
CREATE TABLE TEACHERS
(
   PERSON_ID int,
   ACADEMIC_DEGREE varchar (255),
   UNIQUE
   (
      PERSON_ID,
      ACADEMIC_DEGREE
   )
);
CREATE TABLE ADMINS
(
   PERSON_ID int,
   POSITION varchar (255),
   UNIQUE
   (
      PERSON_ID,
      POSITION
   )
);
CREATE TABLE COURSES
(
   COURSE_ID serial,
   COURSE_NAME varchar (255),
   COURSE_DESCRIPTION varchar (255),
   UNIQUE (COURSE_NAME)
);
CREATE TABLE LECTURES
(
   LECTURE_ID serial,
   TIMESLOT int,
   TEACHER_ID int,
   COURSE_ID int,
   GROUP_ID int,
   ROOM_NUMBER int,
   WEEK int,
   WEEKDAY varchar (255),
   UNIQUE
   (
      ROOM_NUMBER,
      TIMESLOT,
      WEEK,
      WEEKDAY
   )
);